### ISSUE TITLE
Still Active

### ISSUE THREAD

**Issue by btotharye** [tonybaloney/sciencelogic#6]
Just wondering how active this project still is?  I see a few issues in the calls and I think it is due to updated API changes that haven't been updated here.  If it is still being actively maintained here I can push up some PR changes.

Let me know.

Thanks

**Comment by tonybaloney** [comment]
hi @btotharye this library is being actively used in a prod environment and has been since it was authored. I just opened it as there weren't any other EM7 libraries out that I could find.

PR's more than welcome

**Comment by btotharye** [comment]
Ok I'll probably push some changes up then, also out of curiousity is there a reason on the get_devices part you are only giving back the name instead of the full uri output?  We use a lot of custom attributes so I would obviously want to see that.  I could just use the .get to get it though.

**Comment by tonybaloney** [comment]
@btotharye honestly can't remember. We used custom attributes too. IF you can find a way to filter/get by custom attribute that would be amazing. The documented way in the API never worked
